name: vinnaturel
favicon: null
layout_spectrum: 0
typography_spectrum: 0.3273816392756999
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#fdfff4'
    - '#af0000'
    - '#00646b'
    - '#7aae80'
  brandStrength: 1
  lightness: 0.4448622
  saturation: 0.4329574
  rhythmicContrast: 0.4216792
purpose: []
