favicon: null
name: vinnaturel
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.4329574
  brandStrength: 0.5
  lightness: 0.4448622
  brandColors:
    - '#030303'
    - '#fdfff4'
    - '#af0000'
    - '#00646b'
    - '#7aae80'
  rhythmicContrast: 0.4216792
typography_spectrum: 0.3273816392756999
layout_spectrum: 0
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
